name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: actions test
        run: |
          echo "${{ hashFiles('./package-lock.json') }}"
          echo "${{ hashFiles('../../package-lock.json') }}"
          echo "${{ hashFiles('/package-lock.json') }}"
          echo "${{ hashFiles('../../**/package-lock.json') }}"
          echo "${{ hashFiles(format('{0}{1}', github.workspace, './package-lock.json')) }}"
      - name: Get NPM cache directrory
        id: npm-cache
        run: | 
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache NPM
        uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: npm install
        run: |
          npm ci
      - name: lint
        run: |
          npm run lint
      - name: build:prod
        if: github.event_name == 'pull_request'
        run: |
          yarn run build:prod
      - name: actions test2
        run: |
          echo "${{ hashFiles('./package-lock.json') }}"
          echo "${{ hashFiles('../../package-lock.json') }}"
          echo "${{ hashFiles('/package-lock.json') }}"
          echo "${{ hashFiles('../../**/package-lock.json') }}"
          echo "${{ hashFiles(format('{0}{1}', github.workspace, './package-lock.json')) }}"
      - name: test
        if: github.event_name == 'pull_request'
        run: |
          yarn run test -- --watch=false --browsers=ChromeHeadless
        env:
          CI: true
